### ISSUE TITLE
(installed) mobile games are lonely

### ISSUE THREAD

**Issue by glennhartmann** [rknoll/draw#1]
When installed on Android as a WebAPK, the app launches in standalone display mode (meaning that it does not show a URL bar). This makes it quite difficult to share the link to a newly-created game.

![Screenshot_20201109-113505](https://user-images.githubusercontent.com/570079/98574620-26fcdd00-2286-11eb-85c8-608468a099ee.png)

![Screenshot_20201109-113520](https://user-images.githubusercontent.com/570079/98574645-2d8b5480-2286-11eb-8d87-aef8621f93e6.png)

This should be easy to fix (on modern browsers) using the [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by rknoll** [comment]
Thanks for the screenshots, it's also kinda non-intuitive on desktop right now so a dedicated share button would be a nice addition. WDYT?
