### ISSUE TITLE
All good things must come to an end..

### ISSUE THREAD

**Issue by rknoll** [rknoll/draw#12]
The game is currently open-ended which makes it difficult do declare a winner. Maybe we should predefine a number of turns until the game is considered "over" and show a leaderboard with the winner(s) and some interesting stats? If players want another round there should be an easy way to do so.

**Comment by beverloo** [comment]
One observation from our playing the other variants is that we're always _guesstimating_ how much points we'd get through in the available time. Having an option available to set when the game will end will be useful, perhaps even with a suggestion for the (half) hour following the current time.

**Comment by rknoll** [comment]
Time based ending sounds good too, the point system needs a bit of a revamp though as it might not be fair if stopped mid-turn, but that's a separate issue.
