### ISSUE TITLE
it's not obvious which colour the user has selected

### ISSUE THREAD

**Issue by glennhartmann** [rknoll/draw#18]

**Comment by rknoll** [comment]
There actually is a thin border around the selected color and the cursor is filled with the same one. Would it be enough to make the highlighting around the selected color more obvious?

**Comment by glennhartmann** [comment]
Yeah, I think so - the border is very small. When using the smallest brush size, it's also quite difficult to see the colour in the cursor (larger brush sizes are much more clear)
