### ISSUE TITLE
The same word can appear twice to choose from

### ISSUE THREAD

**Issue by rknoll** [rknoll/draw#38]
We only make sure that users don't get already-played words [here](https://github.com/rknoll/draw/blob/main/server/Game.js#L167) but have no check for the currently selected words. This means there is a slight chance a user can get the same word multiple times to choose from, see screenshot.
When fixing this we need to make sure not to end up in an endless loop if the word list contains fewer than 3 words, as is the case for the unmodified demo word list.

![Screenshot 2021-09-07 15 55 44](https://user-images.githubusercontent.com/1607339/132376966-e8027a74-286a-4e36-9ecc-9634bda07a1d.png)

**Comment by odanilo** [comment]
Hey, @rknoll, I'd like to help out with this issue. Is there a specific implemantation you had in mind?

What about this solution? I think that gets the job done.

```js
sendWordCandidates() {
  ...
  const wordsLeft = words.length - this.words.size;
  const maxWordsSend = 3;
  while (candidates.length < maxWordsSend && candidates.length < wordsLeft) {
    const index = Math.floor(Math.random() * words.length);
    const word = words[index];
    const isWordValid = !word || this.words.has(word) || candidates.includes(word);
    
    if (isWordValid) continue;
    candidates.push(word);
  }
  ...
}
```

First we stop the `while` when the `candidates` array reachs the max possible (3) or the amount of words left to pick (in cases where we have fewer than 3 words valids to draw.

After that we check if the `word` draw is included in the `candidates` array before pushing it.

**Comment by rknoll** [comment]
Hey @odanilo, thanks for taking a look at this 😃

My first thoughts were similar to your approach, ~although we'd need to make sure to update `wordsLeft` when we "use" a word and put it into `candidates`. Otherwise we'd fall into the endless loop I described above I think?~ Edit: ah, exiting early should work, but then we'd have less than 3 words to choose from on the client which may be ok? Maybe we should just require that a valid word list has at least 3 words in it?

Another approach would be to replace this while loop with something more deterministic and split it up into these steps:
1. Have an array of available words (either construct it here or replace `this.words` with something like `this.availableWords`)
2. Shuffle the array and use the first or last 3 items (or fewer if there aren't enough) as candidates (alternatively find a way to get a random sample without shuffling the whole array)
3. In `useWord()` remove the chosen word from the available words

To make sure we always have enough words to choose from we can reset the available words like we do [here](https://github.com/rknoll/draw/blob/main/server/Game.js#L163).
What do you think?

**Comment by odanilo** [comment]
I think from a usability point of view it would be nice to always have a list with a lot of words, so I think the idea of making that a requirement or at least a warning. Maybe a suggested minimum amount based on round time would be a good future idea, what do you think?

About the mentioned possible solutions to solve the problem, I believe that both are good.

The first is simpler and uses the logic that already exists in the application and is ready to go.

The second is perhaps a clearer approach and as you said, deterministic.

So that's why I believe it is more a matter of choosing what is most coherent for the application. So tell me which approach you think makes the most sense and I try to execute.

Thanks, @rknoll.

**Comment by rknoll** [comment]
Yeah we can definitely just throw an exception if we start with a wordlist that is too short [here](https://github.com/rknoll/draw/blob/main/server/Game.js#L7).
Would you mind adding some more words [here](https://github.com/rknoll/draw/blob/main/data/words.json#L1) so the server starts up successfully from a clean checkout?

As for the approaches, I'd always be in favour of leaving the place cleaner than it was, so if it's not too much work let's clean this up and try if the `availableWords` approach looks better in the end :-)
