### ISSUE TITLE
Clamp and round draw command coordinates

### ISSUE THREAD

**Issue by rknoll** [rknoll/draw#5]
The server rejects out-of-bound draw commands and we don't need all the extra precision anyway as we don't to aliasing:
```
invalid message: {"type":"line","color":"#D37CAA","width":4,
  "from":{"x":4.84251968503937,"y":305.3177521008403},
  "to":{"x":-0.19685039370078738,"y":302.796743697479}
}
```
Rounding to the nearest integer and clamping to `0x0 - 800x600` should be fine.

**Comment by beverloo** [comment]
Yeah - I used DevTools to resize the canvas to see what the effect would be. Nothing, it turns out. Perhaps a fun mechanism would be to subtract points and publicly shame a player who's issued a normally impossible command? 😃

**Comment by rknoll** [comment]
That explains other unreasonable log entries I was already wondering about 😉  At least now it's still possible to achieve invalid data when scaling down the window and using a big brush, so until that's fixed I wouldn't penalize players. I do like the idea of making it visible who tries to cheat though 😏
